// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD91xzrdbZUsyJG12Vqy5pvjiFmqXB2ap8',
    appId: '1:531116879772:web:5c07d85436c95c5065e259',
    messagingSenderId: '531116879772',
    projectId: 'cni-web1',
    authDomain: 'cni-web1.firebaseapp.com',
    storageBucket: 'cni-web1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC77smqkaf4S9dTnNLCf8bmBBoybf-LpfY',
    appId: '1:531116879772:android:241d7488af122f7c65e259',
    messagingSenderId: '531116879772',
    projectId: 'cni-web1',
    storageBucket: 'cni-web1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuIr_ej1qOJbmkP7ujHChPnkP0RYV0Dbs',
    appId: '1:531116879772:ios:6e501ce6448279dd65e259',
    messagingSenderId: '531116879772',
    projectId: 'cni-web1',
    storageBucket: 'cni-web1.appspot.com',
    iosBundleId: 'com.cni.cniWeb',
  );
}
